# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FundallCodeChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FundallCodeChallenge
  pod 'Alamofire', '~> 5.2'
  pod 'SnapKit', '~> 5.0.0'
  pod 'NVActivityIndicatorView'

  target 'FundallCodeChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FundallCodeChallengeUITests' do
    # Pods for testing
  end

end
